url: "https://mwvanoostende.com"
baseurl: ""

# Site settings
title: Matthijs van Oostende
email: matthijsvanoostende@gmail.com
description: "Matthijs van Oostende. My personal online page."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthijs-van-oostende-2a5643137/
  - title: github
    url: https://github.com/Matth93

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  portfolio:
    permalink: /portfolio/:path/

  certificates:
    permalink: /certificates/:path/


